-- MySQL Script generated by MySQL Workbench
-- 04/10/15 17:30:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwordhash` VARCHAR(64) NOT NULL,
  `passwordsalt` VARCHAR(6) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `sex` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subscriptions` ;

CREATE TABLE IF NOT EXISTS `Subscriptions` (
  `User_id_sub` INT NOT NULL,
  `User_id_own` INT NOT NULL,
  PRIMARY KEY (`User_id_sub`, `User_id_own`),
  CONSTRAINT `fk_Subscriptions_User`
    FOREIGN KEY (`User_id_sub`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscriptions_User1`
    FOREIGN KEY (`User_id_own`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlist` ;

CREATE TABLE IF NOT EXISTS `Playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media` ;

CREATE TABLE IF NOT EXISTS `Media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT 'no description',
  `category` INT NOT NULL DEFAULT 0,
  `extension` VARCHAR(10) NOT NULL,
  `type` INT NOT NULL,
  `share_type` INT NOT NULL DEFAULT 0,
  `download_type` INT NOT NULL DEFAULT 2,
  `allow_discussion` INT NOT NULL DEFAULT 1,
  `allow_rating` INT NOT NULL DEFAULT 1,
  `view_count` INT NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL,
  `rating` FLOAT NOT NULL,
  `filename` VARCHAR(45) NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Media_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlaylistMedias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlaylistMedias` ;

CREATE TABLE IF NOT EXISTS `PlaylistMedias` (
  `Playlist_id` INT NOT NULL,
  `Media_id` INT NOT NULL,
  PRIMARY KEY (`Playlist_id`, `Media_id`),
  CONSTRAINT `fk_PlaylistMedia_Playlist1`
    FOREIGN KEY (`Playlist_id`)
    REFERENCES `Playlist` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlaylistMedia_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FaveriteMedias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FaveriteMedias` ;

CREATE TABLE IF NOT EXISTS `FaveriteMedias` (
  `User_id` INT NOT NULL,
  `Media_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Media_id`),
  CONSTRAINT `fk_Faveritelist_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FaveriteMedias_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Friend` ;

CREATE TABLE IF NOT EXISTS `Friend` (
  `User_id1` INT NOT NULL,
  `User_id2` INT NOT NULL,
  PRIMARY KEY (`User_id1`, `User_id2`),
  CONSTRAINT `fk_Friend_User1`
    FOREIGN KEY (`User_id1`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friend_User2`
    FOREIGN KEY (`User_id2`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contact` ;

CREATE TABLE IF NOT EXISTS `Contact` (
  `User_id1` INT NOT NULL,
  `User_id2` INT NOT NULL,
  PRIMARY KEY (`User_id1`, `User_id2`),
  CONSTRAINT `fk_Contact_User3`
    FOREIGN KEY (`User_id1`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_User4`
    FOREIGN KEY (`User_id2`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Message` ;

CREATE TABLE IF NOT EXISTS `Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `isRead` INT NOT NULL DEFAULT '0',
  `User_id1` INT NOT NULL,
  `User_id2` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_id1`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User2`
    FOREIGN KEY (`User_id2`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Block` ;

CREATE TABLE IF NOT EXISTS `Block` (
  `User_id1` INT NOT NULL,
  `User_id2` INT NOT NULL,
  PRIMARY KEY (`User_id1`, `User_id2`),
  CONSTRAINT `fk_Block_User1`
    FOREIGN KEY (`User_id1`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Block_User2`
    FOREIGN KEY (`User_id2`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Group` ;

CREATE TABLE IF NOT EXISTS `Group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Group_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GroupUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GroupUsers` ;

CREATE TABLE IF NOT EXISTS `GroupUsers` (
  `Group_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Group_id`, `User_id`),
  CONSTRAINT `fk_GroupUsers_Group1`
    FOREIGN KEY (`Group_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GroupUsers_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Topic` ;

CREATE TABLE IF NOT EXISTS `Topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Topic_Group1`
    FOREIGN KEY (`Group_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TopicComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TopicComment` ;

CREATE TABLE IF NOT EXISTS `TopicComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(5000) NOT NULL,
  `date` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Topic_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Topic1`
    FOREIGN KEY (`Topic_id`)
    REFERENCES `Topic` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediaComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediaComment` ;

CREATE TABLE IF NOT EXISTS `MediaComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(5000) NOT NULL,
  `date` DATETIME NOT NULL,
  `Media_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_MediaComment_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MediaComment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediaBlockView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediaBlockView` ;

CREATE TABLE IF NOT EXISTS `MediaBlockView` (
  `Media_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Media_id`, `User_id`),
  CONSTRAINT `fk_MediaBlock_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MediaBlock_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediaKeywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediaKeywords` ;

CREATE TABLE IF NOT EXISTS `MediaKeywords` (
  `keyword` VARCHAR(20) NOT NULL,
  `Media_id` INT NOT NULL,
  PRIMARY KEY (`keyword`, `Media_id`),
  CONSTRAINT `fk_MediaKeywords_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediaRatings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediaRatings` ;

CREATE TABLE IF NOT EXISTS `MediaRatings` (
  `rating` INT NOT NULL,
  `Media_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Media_id`, `User_id`),
  CONSTRAINT `fk_MediaRatings_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MediaRatings_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediaBlockDownload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediaBlockDownload` ;

CREATE TABLE IF NOT EXISTS `MediaBlockDownload` (
  `Media_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Media_id`, `User_id`),
  CONSTRAINT `fk_MediaBlockDownload_Media1`
    FOREIGN KEY (`Media_id`)
    REFERENCES `Media` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MediaBlockDownload_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

